In [ ]:
import numpy as np
import pandas as pd

np.random.seed(1337)  # for reproducibility
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics.classification import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.regression import r2_score, mean_squared_error
from sklearn.preprocessing import MinMaxScaler

from dbn.tensorflow import SupervisedDBNRegression

In [ ]:
# Read the dataset
PM1_FILENAME = "pm1_noeng_output_merged_mmda_wwo_Taft Ave._2015"
PM2_FILENAME = "pm2_noeng_output_merged_mmda_wwo_Taft Ave._2015"
EXT = ".csv"
pm1_output_dataset = pd.read_csv("output/" + PM1_FILENAME + EXT, skipinitialspace=True)
pm2_output_dataset = pd.read_csv("output/" + PM2_FILENAME + EXT, skipinitialspace=True)

##### Preparing Training Dataset

In [ ]:
pm1_output_dataset = pd.read_csv("output/" + PM1_FILENAME + EXT, skipinitialspace=True)
pm2_output_dataset = pd.read_csv("output/" + PM2_FILENAME + EXT, skipinitialspace=True)

print("Start : " + str(pm1_output_dataset.columns[0:pm1_output_dataset.shape[1]][5]))

# print("Start : " + str(original_dataset.columns[0:original_dataset.shape[1]][5]))
# print("End : " + str(original_dataset.columns[0:original_dataset.shape[1]][traffic_dataset.shape[1]-1]))

# # Remove date time. Remove unused columms
# #0-2 = dt + lineName + stationName || 3-4 - statusN - statusS || 5-end - weather variables
# cols_to_remove = [0, 1, 2] + list(range(5, traffic_dataset.shape[1]))

# # #Remove Redundant Variables
# # #Variables = WindspeedKmph, cond, precipMM, humidity, visibility, pressure, cloudcover, dewPointC, windGustKmph, 
# # redundant_variables = [5, 6, 7, 9, 16, 17, 19, 20, 21, 22, 24, 25]
# # cols_to_remove += redundant_variables

# traffic_dataset.drop(traffic_dataset.columns[[cols_to_remove]], axis=1, inplace=True)
# traffic_dataset.head()

##### Preparing Weather Dataset

In [10]:
original_dataset = pd.read_csv("data/mmda-wwo/merged_mmda_wwo_Taft Ave._2015.csv", skipinitialspace=True)
weather_dataset = original_dataset
print("Start : " + str(weather_dataset.columns[0:original_dataset.shape[1]][5]))
print("End : " + str(weather_dataset.columns[0:original_dataset.shape[1]][weather_dataset.shape[1]-1]))

# Remove date time. Remove unused columms
#0-2 = dt + lineName + stationName || 3-4 - statusN - statusS || 5-end - weather variables
cols_to_remove = [0, 1, 2] + [3, 4]

#Remove Redundant Variables
#Variables = tempC WindspeedKmph, cond, precipMM, humidity, visibility, pressure, cloudcover, dewPointC, windGustKmph, 
redundant_variables = [6, 7, 9, 16, 17, 19, 20, 21, 22, 24, 25]
cols_to_remove += redundant_variables

weather_dataset.drop(weather_dataset.columns[[cols_to_remove]], axis=1, inplace=True)
weather_dataset.head()

Start : tempC
End : feelsLikeF

,tempC,windspeedKmph,cond,precipMM,humidity,visibility,pressure,cloudcover,dewPointC,windGustKmph
0,0.2000,0.295455,0.631579,0.0,0.84058,1.0,0.758621,0.330,0.538462,0.236111
1,0.1875,0.295455,0.631579,0.0,0.84058,1.0,0.758621,0.325,0.538462,0.239583
2,0.1750,0.295455,0.631579,0.0,0.84058,1.0,0.758621,0.320,0.538462,0.243056
3,0.1625,0.295455,0.631579,0.0,0.84058,1.0,0.758621,0.315,0.538462,0.246528
4,0.1500,0.295455,0.631579,0.0,0.84058,1.0,0.758621,0.310,0.538462,0.250000

In [11]:
# To-be Predicted variable
Y = traffic_dataset.statusS
Y = Y.round(5)

# Other data
X = weather_dataset
#X = dataset
#X.statusS = X.statusS.round(5)

# Splitting data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1337)
X_train = np.array(X_train)
X_test = np.array(X_test)
Y_train = np.array(Y_train)
Y_test = np.array(Y_test)

# Data scaling
min_max_scaler = MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)

In [12]:
# Training
regressor = SupervisedDBNRegression(hidden_layers_structure=[3],
                                    learning_rate_rbm=0.01,
                                    learning_rate=0.01,
                                    n_epochs_rbm=3,
                                    n_iter_backprop=5,
                                    batch_size=16,
                                    activation_function='relu')
regressor.fit(X_train, Y_train)

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 0.293233
>> Epoch 2 finished 	RBM Reconstruction error 0.205119
>> Epoch 3 finished 	RBM Reconstruction error 0.172956
[END] Pre-training step
[START] Fine tuning step:
>> Epoch 0 finished 	ANN training loss 0.113003
>> Epoch 1 finished 	ANN training loss 0.110848
>> Epoch 2 finished 	ANN training loss 0.109246
>> Epoch 3 finished 	ANN training loss 0.108042
>> Epoch 4 finished 	ANN training loss 0.106840
[END] Fine tuning step

SupervisedDBNRegression(batch_size=16, dropout_p=0, l2_regularization=1.0,
            learning_rate=0.01, n_iter_backprop=5, verbose=True)

In [13]:
# Test
X_test = min_max_scaler.transform(X_test)
Y_pred = regressor.predict(X_test)
print('Done.\nR-squared: %f\nMSE: %f' % (r2_score(Y_test, Y_pred), mean_squared_error(Y_test, Y_pred)))

Done.
R-squared: 0.111717
MSE: 0.110200

In [14]:
print(len(Y_pred))
temp = []
for i in range(len(Y_pred)):
    temp.append(Y_pred[i][0])
d = {'Predicted': temp, 'Actual': Y_test}

df = pd.DataFrame(data=d)
df.head()

7008

   Actual  Predicted
0     0.0   0.466735
1     1.0   0.555908
2     1.0   0.589064
3     0.5   0.784301
4     0.5   0.742655

In [15]:
df

       Actual  Predicted
0     0.00000   0.466735
1     1.00000   0.555908
2     1.00000   0.589064
3     0.50000   0.784301
4     0.50000   0.742655
5     1.00000   0.610054
6     0.32828   0.489121
7     1.00000   0.511767
8     1.00000   0.631453
9     0.00000   0.519495
10    0.50000   0.670532
11    1.00000   0.605440
12    1.00000   0.780322
13    0.00000   0.536278
14    0.50000   0.733593
15    0.50000   0.791572
16    0.00000   0.574487
17    0.00000   0.494279
18    0.50000   0.767270
19    0.50000   0.591393
20    0.50000   0.492118
21    0.50000   0.728196
22    1.00000   0.543990
23    0.50000   0.664687
24    0.50000   0.618251
25    0.50000   0.696661
26    1.00000   0.800034
27    1.00000   0.532614
28    0.00000   0.459388
29    0.29032   0.557292
...       ...        ...
6978  1.00000   0.669854
6979  0.50000   0.816803
6980  0.50000   0.545171
6981  0.50000   0.489584
6982  0.50000   0.584696
6983  0.50000   0.606578
6984  1.00000   0.768150
6985  0.00000   0.599023
6986  0.50000   0.596805
6987  1.00000   0.592624
6988  1.00000   0.849319
6989  0.50000   0.630664
6990  1.00000   0.797535
6991  0.50000   0.627797
6992  1.00000   0.590357
6993  1.00000   0.664067
6994  0.50000   0.499887
6995  0.50000   0.590691
6996  0.50000   0.563125
6997  0.50000   0.559553
6998  0.50000   0.580741
6999  1.00000   0.629489
7000  0.50000   0.500701
7001  0.50000   0.794601
7002  1.00000   0.498341
7003  1.00000   0.596534
7004  0.00000   0.763057
7005  0.50000   0.559445
7006  0.50000   0.560756
7007  1.00000   0.713919

[7008 rows x 2 columns]

In [16]:
# Save the model
regressor.save('models/pm2-noeng.pkl')

# # Restore
# classifier = SupervisedDBNClassification.load('model.pkl')

# # Test
# Y_pred = classifier.predict(X_test)
# print('Done.\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))

In [19]:
FILENAME = "merged_mmda_wwo_Taft Ave._2015"
EXT = ".csv"
df.to_csv("output/pm2_noeng_output_" + FILENAME + EXT, encoding='utf-8', index=False)